services:
  database:
    image: 'postgres:latest'
    container_name: 'reservation-system-db'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_USER}'
      - 'POSTGRES_USER=${POSTGRES_PASSWORD}'
    ports:
      - '5432'
