services:
  database:
    image: 'postgres:latest'
    container_name: 'reservation-system-db'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - 'app_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  app_data:
